In [31]:
import matplotlib.pyplot as plt
import numpy as np

t = [0, 1/5, 2/5, 3/5,3/5,3/5,4/5,4/5,4/5,5/5,5/5,5/5]
s = [1/7,1/7,1/7,1/7,2/7,3/7,3/7,4/7,5/7,5/7,6/7,7/7]
plt.xticks(np.arange(0.000, max(s)+1, 1/7))
plt.yticks(np.arange(0.000, max(t)+1, 1/5))
plt.xlim(0.0, 1.143)
plt.ylim(0.0, 1.2)
plt.plot(s, t,marker='o')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) curve')
plt.grid(True)
plt.savefig("test.png")
plt.show()

In [2]:
from sklearn.datasets import load_breast_cancer
#from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score,precision_score,recall_score,roc_auc_score
import numpy as np

data_X,data_Y = load_breast_cancer(True)

lr = LogisticRegression()

acc = cross_val_score(lr, data_X, data_Y, cv=5,scoring='accuracy')
print(acc)
print("Accuracy : %0.3f"%np.mean(acc))

pre = cross_val_score(lr, data_X, data_Y, cv=5,scoring='precision')
print(pre)
print("Precision : %0.3f"%np.mean(pre))

rec = cross_val_score(lr, data_X, data_Y, cv=5,scoring='recall')
print(rec)
print("Recall : %0.3f"%np.mean(rec))

auc = cross_val_score(lr, data_X, data_Y, cv=5,scoring='roc_auc')
print(auc)
print("AUC : %0.3f"%np.mean(auc))




[ 0.93913043  0.93043478  0.97345133  0.94690265  0.96460177]
Accuracy : 0.951
[ 0.91139241  0.92105263  0.97222222  0.95774648  0.98550725]
Precision : 0.950
[ 1.          0.97222222  0.98591549  0.95774648  0.95774648]
Recall : 0.975
[ 0.98998708  0.99257106  0.99765258  0.98289738  0.99765258]
AUC : 0.992
